### ISSUE TITLE
CCF instead of MAF?

### ISSUE THREAD

**Issue by jh2663** [marcjwilliams1/SubClonalSelection.jl#20]
Hi, I am just wondering if you have ever thought about using CCF (cancer cell fraction) of mutations instead of the original MAF values to run your subclonal selection analysis. I have multiple tumor sequencing data but most of them have gotten severe CNVs. I just want to give a try SubClonalSelection for even those samples. I have all the purity and CNV estimates for each of mutations so can get CCFs easily. 

Best,

**Comment by marcjwilliams1** [comment]
Hi @jh2663, thanks for your interest in SubClonalSelection. 

In theory yes CCF would work and would be best, however it depends on how the CCF calculation is done. In my experience, this can be tricky to do well and get CCF values suitable to be used in the model. 

The model expects there to be a single "clonal" peak and then infers the evolutionary dynamics from the subclonal mutations (as in the [examples](https://github.com/marcjwilliams1/SubClonalSelection.jl/tree/master/example)).

So the tricky thing with the CCF calculation is how to get a single "clonal" peak. Eg this as an example of VAF histograms corrected for cellularity in different segments (lines here are the expected location of clonal peaks)
![Screen Shot 2019-07-05 at 12 00 53](https://user-images.githubusercontent.com/9133916/60719477-b7ebd780-9f1f-11e9-93dc-b343262fe2fe.png)

So in non heterozygous diploid regions you'll see multiple clonal peaks due to mutations accumulating before or after chromosome gains. The model currently won't take that into account so it depends if the method you use to convert MAF to CCF takes this into account and results in a distribution that looks like the diploid case (left plot) or not. 

We're currently working on better methods to do this that can use CCFs or fit models for regions of the genome that are non-diploid (https://www.biorxiv.org/content/biorxiv/early/2019/03/26/586560.full.pdf). We will try and release the code and package sometime over the summer.

**Comment by jh2663** [comment]
Really nice to hear this. I look forward seeing your new package soon. 

all the best,
